### ISSUE TITLE
Hey! Would it be possible to link this repo to wasm-tools?

### ISSUE THREAD

**Issue by chrisdickinson** [WebAssembly/wasi-tools#16]
Hey folks! I ran into this repo early on when starting some research on WASM & WASI. It's named pretty similarly to the [`wasm-tools`](github.com/bytecodealliance/wasm-tools) repo which seems to fill the intended purpose of this repo. (`wasi-` and `wasm-` can be easy to get switched up, especially when you're just getting started in the ecosystem!)

Would it make sense to push a README commit to this repo pointing incoming readers at `wasm-tools`? (Would it also make sense to archive this repo? I'm not sure what the state of it is – it might be here in preparation for more tools to land, in which case I totally understand not archiving it.)

(Great work on WASM & WASI, btw!)

**Comment by sunfishcode** [comment]
I'm thinking it makes sense to phase this repo out and archive it. We do still use it in the github actions in repos generated from the wasi-proposal-template repo, but we should switch that to wit-bindgen.

**Comment by sunfishcode** [comment]
This switch has [now happened](https://github.com/WebAssembly/wit-abi-up-to-date/pull/16/).

**Comment by sunfishcode** [comment]
I've filed to explain the purpose of this repo and link to wit-bindgen.

**Comment by sunfishcode** [comment]
That is, I've filed https://github.com/WebAssembly/wasi-tools/pull/19 to this.

**Comment by sunfishcode** [comment]
#19 is now merged; I'll now archive this repo.
