### ISSUE TITLE
`wit-abi` gets confused about imports

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-tools#17]
Looking at the Markdown/HTML produced for wasi-nn, this tool seems to confuse the Markdown parser whether it should convert several lines to Markdown or print them as HTML: [`ml.md`](https://github.com/WebAssembly/wasi-nn/blob/main/ml.md#types-3). `wit-abi` happily produces intermixed Markdown and HTML until it gets to a point (I believe related to imports?) where it dumps something that gets displayed as:

```
#### `type tensor` [`tensor`](#tensor)

#### `type tensor-data` [`tensor-data`](#tensor_data)

#### `type graph` [`graph`](#graph)

#### `type graph-execution-context` `u32`
```

This is not a high priority issue but I thought I would report it while it's on my mind.

**Comment by sunfishcode** [comment]
Thanks for the report! The code that handles this lives in wit-bindgen; would you mind filing this report in [the wit-bindgen repo](https://github.com/bytecodealliance/wit-bindgen)?

**Comment by abrown** [comment]
Moved!
