### ISSUE TITLE
Update wit-abi for variant change in wit-bindgen

### ISSUE THREAD

**Issue by linclark** [WebAssembly/wasi-tools#2]
It looks like `wit-bindgen` has changed RE: variants. However, `wit-abi` was not updated. I found this because of the [CI failure here](https://github.com/WebAssembly/wasi-url/runs/6181714976?check_suite_focus=true).

**Comment by sunfishcode** [comment]
wasi-random and wasi-clocks now both have PRs hitting this failure too.
