### ISSUE TITLE
Release new version of `wit-abi`

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-tools#4]
With the latest changes to WIT brought in a few weeks ago, I noticed some differences between the syntax allowed by a locally-built `wit-abi` and the `wit-abi` installed by the GitHub action, `wit-abi-up-to-date`. To fix this, I think we need to do the following:
 - tag https://github.com/WebAssembly/wasi-tools with `wit-abi-0.2.0`
 - update the `default` field in https://github.com/WebAssembly/wit-abi-up-to-date/blob/main/action.yml to use that tag
 - tag https://github.com/WebAssembly/wit-abi-up-to-date with `v4`

**Comment by abrown** [comment]
I don't have permissions to do the above in either repository or I would do this myself.

**Comment by sunfishcode** [comment]
I think I can do this.

**Comment by sunfishcode** [comment]
https://github.com/WebAssembly/wasi-tools/releases/tag/wit-abi-0.2.0

**Comment by sunfishcode** [comment]
The wit-abi-up-to-date PR is now up: https://github.com/WebAssembly/wit-abi-up-to-date/pull/5

**Comment by sunfishcode** [comment]
It's now merged, and wit-abi-up-to-date is now tagged [v4](https://github.com/WebAssembly/wit-abi-up-to-date/releases/tag/v4).

**Comment by abrown** [comment]
Thanks!
